Prevent counter leak that causes failures within power accounting gathering.
The issue manifests as slurmd reporting the following error when power stats
are requested:

    error: _rpc_acct_gather_energy: Too many pending requests

In turn slurmstepd reports the following error repeatedly in job logs:

    error: _get_joules_task: can't get info from slurmd

Anecdotal evidence suggests this patch mitigates this condition.